### ISSUE TITLE
Create the Kanban board for the project

### ISSUE THREAD

**Issue by nevisende** [lily-coder/recipe-app#10]
Our Repo Project:  https://github.com/lily-coder/recipe-app/projects/1
There are two people in the group:
 - [Lilian Moraa](https://github.com/lily-coder)
 - [Furkan Denizhan](https://github.com/nevisende)

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @nevisende and @lily-coder,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted an Issue linking to your repo, whereas you are required to link to your Kanban board itself

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by nevisende** [comment]
> 

Can you check out the descriptions page please, and this is the associated part:
![Screenshot from 2022-04-19 14-52-06](https://user-images.githubusercontent.com/84407337/163997634-88a03efc-4ac1-451a-9d69-7f7625af2135.png)

**Comment by nevisende** [comment]
> @nevisende in your repo, your Kanban is under the **Projects** tab. That is what is being referred to here, not repo. Failure to provide the link to your project there warrants invalidation.

@TedLivist Please tell me the solution also.

**Comment by TedLivist** [comment]
@nevisende simply edit the link in your issue above from the repo link to the Kanban link here: [https://github.com/lily-coder/recipe-app/projects/1](https://github.com/lily-coder/recipe-app/projects/1)

**Comment by nevisende** [comment]
> @nevisende simply edit the link in your issue above from the repo link to the Kanban link here: https://github.com/lily-coder/recipe-app/projects/1

@TedLivist Thank you.

**Comment by Mihndim2020** [comment]
### Hi Team, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Descriptive issue summary.

There are some issues that you still need to work on to get this project approved, but you are almost there!
![ALMOST-MINION](https://user-images.githubusercontent.com/65852621/133680327-431cb21d-ad7c-483a-84eb-21b733980a04.png)

# Status: Requires Changes ♻️
_Check the comments below._

- [ ] Please make sure the following `columns` are present on your `kanban board`, `To do`, `In Progress`, `In Review`, `Done`. Please kindly add `In Review` column on your `kanban board`, since you will be giving each other  code reviews during the implementation of your app. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @nevisende and @lily-coder,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
